# https://hub.docker.com/r/andyshinn/dnsmasq/
version: '3'
services:
  dnsmasq:
    image: jtmilan/dnsmasq
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    cap_add:
      - NET_ADMIN
    networks:
      - dns
    command: --log-facility=-
    volumes:
      - ./data/dnsmasq.conf:/etc/dnsmasq.conf
      - ./data/dnsmasq.d:/etc/dnsmasq.d
      - ./data/resolv-dnsmasq.conf:/etc/resolv-dnsmasq.conf
      - ./data/resolv.conf:/etc/resolv.conf

networks:
    dns:
        driver: bridge